export const START_LOADING = 'PIN_ADD_ERROR';
export const NOT_LOADING = 'PIN_ADD_ERROR';

export const LOGIN_USER_REQ = 'LOGIN_USER_REQ';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';

export const REGISTER_USER_REQ = 'REGISTER_USER_REQ';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';

export const PIN_ADD_ERROR = 'PIN_ADD_ERROR';
export const PIN_ADD_SUCCESS = 'PIN_ADD_SUCCESS';

export const PIN_GET_SUCCESS = 'PIN_GET_SUCCESS';
export const PIN_GET_ERROR = 'PIN_GET_ERROR';